### ISSUE TITLE
Support acting on additional html files

### ISSUE THREAD

**Issue by razor-x** [gpoitch/ember-cli-html-minifier#2]
It seems this only acts on `index.html`:

https://github.com/gdub22/ember-cli-html-minifier/blob/f9bcb88907eb42014e2f60c887e4596b9934a9cb/index.js#L44

``` js
var htmlFilePath = this.app.options.outputPaths.app.html || 'index.html';
```

Would it be possible to act on additional html files? Either automatically or by manual include / exclude options?

The specific use case I ran into is that [Vulcanize](https://github.com/polymer/vulcanize) split out minification and delegated it to the overall asset pipeline. So now the generated `assets/vulcanized.html` file must be minified via broccoli. Here is a full example: https://github.com/rxlabs/ember-experiments/blob/1f689196d325cdbc4ff93ce4721f6bb90d08415a/ember-cli-build.js#L39-L48

**Comment by gpoitch** [comment]
I'd accept a PR that changes the lookup to find all html files in the project and minify them.

**Comment by razor-x** [comment]
I'm not as familiar with Broccoli's tree system as with some of the other build pipelines. Not sure exactly when or if I will be able to get to this (it's not urgent at the moment).

My initial approach would be something like (please excuse the rough code)

``` js
// Defaults would be:
// options.appHTML = true
// options.allHTML = false
// options.include = []
// options.exclude = []

function getAllHTMLFiles() {
  // Need to write this (does this search the physical disk or the tree object?)
}

var htmlFilePaths = options.include
var htmlFilePath = this.app.options.outputPaths.app.html || 'index.html';

if (options.all) {
  htmlFilePaths.concat(getAllHTMLFiles());
  if (!options.appHTML) { // remove htmlFilePath from htmlFilePaths }
} elseif(options.appHTML) {
  htmlFilePaths.push(htmlFilePath);
}

//
// Code to remove elements in options.exclude from htmlFilePaths
//

var htmlFileTree = new Funnel( tree, {
  files: htmlFilePaths
});
```

**Comment by gpoitch** [comment]
Check out the docs for [broccoli-funnel](https://github.com/broccolijs/broccoli-funnel), which should be able to do all the work.

**Comment by gpoitch** [comment]
Supported in 0.1.3
https://github.com/gdub22/ember-cli-html-minifier/pull/3
