### ISSUE TITLE
Breaks fastboot

### ISSUE THREAD

**Issue by Redsandro** [gpoitch/ember-cli-html-minifier#6]
Trying `0.2.0`, the minified output from my app is non-fastboot. Even though [this suggests](https://github.com/gdub22/ember-cli-html-minifier/commit/3560fb39174ffc20307b8da9cb0cda020f1767b6) fastboot is taken into account?

**Comment by Redsandro** [comment]
@gdub22 any comment before close? :smiley:

**Comment by gpoitch** [comment]
https://github.com/gdub22/ember-cli-html-minifier/pull/7
