### ISSUE TITLE
Options do not seem to be passed

### ISSUE THREAD

**Issue by RobbieTheWagner** [gpoitch/ember-cli-html-minifier#8]
If I pass `false` for all options, everything is still minified. Should https://github.com/gpoitch/ember-cli-html-minifier/blob/master/index.js#L21 be `this.options.minifierOptions` instead? Not sure why no options are passed through.

**Comment by gpoitch** [comment]
Hey sorry I missed this.  Let me know if it's still an issue. The code looks correct.

**Comment by RobbieTheWagner** [comment]
It was definitely an issue. Unless a fix was implemented, I would assume it still is.

**Comment by gpoitch** [comment]
This is pretty inactive but I'd look at some code if you want to provide it.
